# Generated by Django 3.0.6 on 2020-05-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyaccount',
            name='survey_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
