# Generated by Django 3.0.6 on 2020-05-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200518_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyaccount',
            name='last_survey',
            field=models.DateField(blank=True, null=True),
        ),
    ]
