# Generated by Django 3.0.6 on 2020-05-26 13:14

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('openhumans', '0001_initial'),
        ('main', '0003_surveyaccount_last_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.TextField(default=main.models.create_token)),
                ('minutes_valid', models.IntegerField(default=1440)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openhumans.OpenHumansMember')),
            ],
        ),
    ]
