# Generated by Django 3.0.6 on 2020-06-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_surveyaccount_consent_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyaccount',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
