# Generated by Django 3.0.6 on 2020-06-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_surveyaccount_last_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyaccount',
            name='daily_emails_activated',
            field=models.BooleanField(default=True),
        ),
    ]
